export const Icons = {
	// ------------- technologies -------------
	HTML: "akar-icons:html-fill",
	CSS: "simple-icons:css",
	JAVASCRIPT: "akar-icons:javascript-fill",
	TYPESCRIPT: "akar-icons:typescript-fill",
	REACT_JS: "simple-icons:react",
	NEXT_JS: "akar-icons:nextjs-fill",
	SVELTE_KIT: "simple-icons:svelte",
	REDUX: "simple-icons:redux",
	NODE_JS: "akar-icons:node-fill",
	EXPRESS_JS: "simple-icons:express",
	POSTGRES: "simple-icons:postgresql",
	MONGO_DB: "simple-icons:mongodb",
	PRISMA_ORM: "simple-icons:prisma",
	SEQUELIZE_ORM: "simple-icons:sequelize",
	MONGOOSE: "simple-icons:mongoose",
	JEST: "simple-icons:jest",
	MOCHA: "devicon-plain:mocha",
	CYPRESS: "simple-icons:cypress",
	INSOMNIA: "simple-icons:insomnia",
	HEROKU: "simple-icons:heroku",
	NETLIFY: "simple-icons:netlify",
	VERCEL: "simple-icons:vercel",
	SUPABASE: "simple-icons:supabase",
	TAILWINDCSS: "simple-icons:tailwindcss",
	SHADCN_UI: "simple-icons:shadcnui",
	MATERIAL_UI: "devicon-plain:materialui",
	BOOTSTRAP: "akar-icons:bootstrap-fill",
	SASS: "cib:sass-alt",
	LESS: "simple-icons:less",
	POST_CSS: "simple-icons:postcss",
	STYLED_COMPONENTS: "simple-icons:styledcomponents",
	GIT: "simple-icons:git",
	DOCKER: "simple-icons:docker",
	VITE: "file-icons:vite",
	ESLINT: "simple-icons:eslint",
	PRETTIER: "simple-icons:prettier",
	SHADCN_SVELTE: "simple-icons:shadcnui",
	ESLINT_PLUGIN_SVELTE: "simple-icons:eslint",
	PRETTIER_PLUGIN_SVELTE: "simple-icons:prettier",
	AXIOS: "simple-icons:axios",
	REACT_ROUTER: "simple-icons:reactrouter",
	CHAI: "simple-icons:chai",
	LOTTIE: "uil:lottiefiles-alt",

	// ------------- languages -------------
	LIBGDX: "devicon-plain:libgdx",
	JAVA: "devicon-plain:java",
	GODOT: "simple-icons:godotengine",
	TERMINAL: "lucide:square-terminal",
	PYTHON: "simple-icons:python",
	GITHUB: "streamline-logos:github-logo-2-solid",

	// ------------- categories -------------
	FRONT_END: "lucide:monitor",
	BACK_END: "lucide:server",
	TESTING: "lucide:bug",
	HOSTING: "lucide:network",
	STYLING: "lucide:paintbrush",
	DEVELOPMENT: "lucide:code-xml",

	// ------------- theme -------------
	THEME_DARK: "lucide:moon",
	THEME_LIGHT: "lucide:sun",
	THEME_SYSTEM: "lucide:monitor-cog",

	// ------------- other -------------
	GLOBE: "mynaui:globe",
	EXTERNAL_LINK: "lucide:external-link",
	MOUSE_CLICK: "lucide:mouse-pointer-click",
	CHEVRON_UP: "lucide:chevron-up",
	CHEVRON_DOWN: "lucide:chevron-down",
};
